const cats=['추천','음식배달','패션','디지털','가구/생활','식품','주문내역'];
const baseNames={
'음식배달':['따뜻한 제육 도시락','김치찌개 한상','바삭 치킨 박스','샐러드 정식','수제 버거 세트','마라탕 세트','돈까스 정식','초밥 모둠'],
'패션':['코튼 후드 집업','오버핏 셔츠','와이드 데님 팬츠','데일리 스니커즈','미니 크로스백','니트 카디건','쿨링 반팔티','라이트 조거팬츠'],
'디지털':['무선 마우스','기계식 키보드','블루투스 스피커','노이즈 헤드셋','휴대폰 케이스','충전 독','태블릿 거치대','보조배터리'],
'가구/생활':['원목 의자','패브릭 소파','테이블 램프','라운드 테이블','호텔식 침구','수납 바스켓','미니 선반','러그 매트'],
'식품':['프리미엄 라면','콜드브루 커피','계절 과일박스','베이커리 세트','즉석밥 묶음','냉동 만두','닭가슴살 팩','요거트 세트']
};
const priceBase={'음식배달':9000,'패션':39000,'디지털':26000,'가구/생활':59000,'식품':12800};
const imgCount=120;
let products=[], cart=[], orders=JSON.parse(localStorage.orders||'[]'), home=JSON.parse(localStorage.home||'null'), filter='추천';
function won(n){return n.toLocaleString('ko-KR')+'원'}
function makeProducts(){let id=1; for(let i=0;i<5000;i++){let cat=Object.keys(baseNames)[i%5]; let arr=baseNames[cat]; let nm=arr[i%arr.length]; let grade=['베이직','프리미엄','스페셜','시그니처','라이트'][Math.floor(i/37)%5]; let price=Math.round((priceBase[cat]+(i%23)*1300+(Math.floor(i/11)%17)*900)*(cat==='가구/생활'?1.2:1)/100)*100; products.push({id:id++,cat,name:`${grade} ${nm} ${String(i%99+1).padStart(2,'0')}`,price,img:`assets/products/product_${String((i%imgCount)+1).padStart(3,'0')}.jpg`,rate:(4.5+(i%5)*.1).toFixed(1),sold:120+(i*17)%9000,fast:i%3===0});}}
function renderTabs(){tabs.innerHTML=cats.map(c=>`<button class="${c===filter?'on':''}" onclick="setFilter('${c}')">${c}</button>`).join('')}
function setFilter(c){filter=c;renderTabs();render()}
function list(){let q=document.getElementById('q').value.trim(); if(filter==='주문내역')return []; return products.filter(p=>(filter==='추천'||p.cat===filter)&&(!q||p.name.includes(q)||p.cat.includes(q))).slice(0,80)}
function render(){if(filter==='주문내역'){grid.innerHTML=orders.length?orders.map(o=>`<article class="card" onclick="openTrack('${o.type}')"><img src="${o.img}"><div class="info"><div class="name">${o.name}</div><div class="meta">${o.type==='food'?'음식배달':'택배배송'} · ${o.time}</div><div class="price">${won(o.price)}</div><div class="ship">배송 추적 열기</div></div></article>`).join(''):'<p style="padding:20px">주문내역이 아직 없습니다.</p>';return}
 grid.innerHTML=list().map(p=>`<article class="card" onclick="detail(${p.id})"><img loading="lazy" src="${p.img}"><div class="info"><div class="name">${p.name}</div><div class="meta">★ ${p.rate} · ${p.sold.toLocaleString()}개 구매</div><div class="price">${won(p.price)}</div><div class="ship">${p.cat==='음식배달'?'오늘 배달 가능':'빠른배송 가능'}</div></div></article>`).join('')}
function detail(id){let p=products.find(x=>x.id===id); panelTitle.textContent=p.name; panelBody.innerHTML=`<img class="detailImg" src="${p.img}"><div class="detail"><span class="pill">${p.cat}</span><span class="pill">실시간 추적</span><h2>${p.name}</h2><div class="meta">★ ${p.rate} · 누적 ${p.sold.toLocaleString()}개 구매</div><div class="price">${won(p.price)}</div><p class="mini">상품별 실제 시세 느낌에 맞춰 가격대를 나누고, 배송/배달 흐름이 자연스럽게 보이도록 구성했습니다.</p><div class="row"><button class="ghost" onclick="addCart(${p.id})">장바구니</button><button class="buy" onclick="buyNow(${p.id})">구매하기</button></div><div class="review"><b>구매후기</b><p>사진이랑 거의 비슷하고 포장 상태도 괜찮았어요. 배송 흐름이 바로 보여서 편했습니다.</p></div><div class="review"><b>상세정보</b><p>옵션 선택, 주문, 결제완료, 조리/포장, 배송출발 단계가 모두 동작합니다.</p></div></div>`; panel.classList.add('show')}
function addCart(id){cart.push(products.find(p=>p.id===id)); cartN.textContent=cart.length; alert('장바구니에 담았어요')}
function buyNow(id){let p=products.find(x=>x.id===id); let type=p.cat==='음식배달'?'food':'parcel'; let prep=type==='food'?rand(12,28):rand(45,180); orders.unshift({name:p.name,price:p.price,img:p.img,type,time:new Date().toLocaleString('ko-KR'),prep}); localStorage.orders=JSON.stringify(orders.slice(0,50)); panel.classList.remove('show'); openTrack(type,prep)}
function rand(a,b){return Math.floor(a+Math.random()*(b-a+1))}
closePanel.onclick=()=>panel.classList.remove('show'); closeMap.onclick=()=>track.classList.remove('show'); q.oninput=render;
locBtn.onclick=()=>openHomePanel();
function openHomePanel(){panelTitle.textContent='우리집 설정'; panelBody.innerHTML=`<div class="detail"><h2>배송 받을 위치</h2><p class="mini">현재 위치 허용 또는 주소 검색으로 우리집을 설정할 수 있습니다.</p><button class="buy" onclick="useGPS()">현재 위치로 설정</button><div class="addr"><input id="addrQ" placeholder="예: 서울 강남역, 울산 삼산동"><button onclick="searchAddr()">검색</button></div><div id="addrResult"></div></div>`; panel.classList.add('show')}
function useGPS(){navigator.geolocation?.getCurrentPosition(pos=>{home={lat:pos.coords.latitude,lng:pos.coords.longitude,label:'현재 위치'}; localStorage.home=JSON.stringify(home); alert('우리집 위치를 설정했어요'); panel.classList.remove('show')},()=>alert('위치 권한이 막혔어요. 주소 검색을 이용해 주세요.'),{enableHighAccuracy:true,timeout:9000})}
async function searchAddr(){let q=addrQ.value.trim(); if(!q)return; addrResult.textContent='검색 중...'; try{let r=await fetch(`https://nominatim.openstreetmap.org/search?format=json&limit=5&q=${encodeURIComponent(q)}`);let j=await r.json(); addrResult.innerHTML=j.map(x=>`<div class="review" onclick="setHome(${x.lat},${x.lon},'${String(x.display_name).replaceAll("'","")}')"><b>${x.display_name.split(',').slice(0,2).join(' ')}</b><p class="mini">이 위치로 설정</p></div>`).join('')||'결과 없음'}catch(e){addrResult.textContent='주소 검색은 인터넷 연결이 필요해요.'}}
function setHome(lat,lng,label){home={lat:+lat,lng:+lng,label}; localStorage.home=JSON.stringify(home); alert('우리집 위치를 설정했어요'); panel.classList.remove('show')}
let map, routeLine, marker, animTimer;
async function openTrack(type='parcel',prep){track.classList.add('show'); setTimeout(()=>drawMap(type,prep),100)}
async function drawMap(type,prep){if(!home){routeText.textContent='우리집을 먼저 설정해 주세요. 임시 위치로 표시합니다.'; home={lat:37.5665,lng:126.9780,label:'임시 위치'}} let shop= type==='food'? nearby(home,.018):nearby(home,.055); if(!map){map=L.map('map').setView([home.lat,home.lng],14); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map)} map.eachLayer(l=>{if(l instanceof L.Marker||l instanceof L.Polyline) map.removeLayer(l)}); let points=[]; try{let url=`https://router.project-osrm.org/route/v1/driving/${shop.lng},${shop.lat};${home.lng},${home.lat}?overview=full&geometries=geojson`;let r=await fetch(url);let j=await r.json();points=j.routes[0].geometry.coordinates.map(c=>[c[1],c[0]])}catch(e){points=[[shop.lat,shop.lng],[home.lat,home.lng]]}
 routeLine=L.polyline(points,{weight:6,opacity:.75}).addTo(map); map.fitBounds(routeLine.getBounds(),{padding:[30,30]}); L.marker([home.lat,home.lng]).addTo(map).bindPopup('우리집'); marker=L.marker(points[0],{icon:L.divIcon({className:'',html:`<div style="font-size:30px;filter:drop-shadow(0 5px 5px #0004)">${type==='food'?'🏍️':'🚚'}</div>`,iconSize:[38,38]})}).addTo(map);
 let prepMin=prep||(type==='food'?rand(12,28):rand(60,180)); let moveMin=type==='food'?rand(14,32):rand(35,90); eta.textContent=type==='food'?`조리 ${prepMin}분 + 배달 ${moveMin}분 예상`:`포장/집화 ${prepMin}분 + 배송 ${moveMin}분 예상`; routeText.textContent='실제 지도 도로 경로를 따라 이동 중입니다.'; clearInterval(animTimer); let i=0; animTimer=setInterval(()=>{let t=i/(points.length-1); let idx=Math.min(points.length-1,Math.floor(t*(points.length-1))); marker.setLatLng(points[idx]); bar.style.width=Math.min(100,Math.round(t*100))+'%'; i++; if(i>points.length-1){clearInterval(animTimer); eta.textContent='도착 완료'; bar.style.width='100%'}}, Math.max(80,7000/points.length));}
function nearby(h,d){let a=Math.random()*Math.PI*2;return{lat:h.lat+Math.sin(a)*d,lng:h.lng+Math.cos(a)*d}}
document.querySelectorAll('footer button').forEach(b=>b.onclick=()=>{let g=b.dataset.go;if(g==='track')openTrack('parcel');else if(g==='order')setFilter('주문내역');else if(g==='food')setFilter('음식배달');else setFilter('추천')});
makeProducts();renderTabs();render();
